/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * ul1_nvram_editor.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *    This file contains `vendor' defined logical data items stored in NVRAM.
 *    These logical data items are used in object code of Protocol Stack software.
 *
 *    As for customizable logical data items, they are defined in nvram_user_config.c
 *
 * Author:
 * -------
 * 
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef __UL1_NVRAM_EDITOR_H__
#define __UL1_NVRAM_EDITOR_H__
#ifndef NVRAM_NOT_PRESENT

/* In case of that not to build this file in 2G projects or 3G TDD projects */
#if defined (__MTK_UL1_FDD__)

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */ 

/*
 *   Include Headers
 */
 
/*
 *   NVRAM Basic Headers
 */
#include "nvram_data_items.h"

/*
 *   User Headers
 */
#include "ul1_nvram_def.h"


#ifdef GEN_FOR_PC
BEGIN_NVRAM_DATA 
 
#if (defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__)) 
 

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_3G_RF_PARAMETER_LID)
     U_sUl1dRfCustomInputData * NVRAM_EF_UL1_3G_RF_PARAMETER_TOTAL
     {
        startPattern:"#U_0x1234ABCD_L_0x1234ABCD"
        {
        };
        structVersion:""
        {
        };
        rfType:""
        {
        };
        isDataUpdate:"#U_1_L_1"
        {
        };
        umtsRfPaControlTimingOffset:""
        {
        };
        umtsRfPaControlTimingOffset.maxOffset:"#U_65535"
        {
        };
        umtsRfPaControlTimingOffset.vmOffset:"#U_65535"
        {
        };
        umtsRfPaControlTimingOffset.vbiasOffset:"#U_65535"
        {
        };
        umtsRfPaControlTimingOffset.dc2dcOffset:"#U_65535"
        {
        };
        umtsRfPaControlTimingOffset.vgaOffset:"#U_65535"
        {
        };
        umtsBsiBpiTiming:""
        {
        };
        umtsBsiBpiTiming.xTC_PR1:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PR2:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PR2B:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PR3:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PR3A:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PT1:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PT2:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PT2B:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PT3:"#U_32767"
        {
        };
        umtsBsiBpiTiming.xTC_PT3A:"#U_32767"
        {
        };
        umtsPdata:""
        {
        };
        umtsBandIndicator:""
        {
        };
        umtsRxLnaPortSel:""
        {
        };
        umtsTxPathSel:""
        {
        };
        xPMU_PA_CONTROL:""
        {
        };
        endPattern:"#U_0xABCD1234_L_0xABCD1234"
        {
        };
     };

#endif /* #if (defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__)) */

#if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__) 
LID_BIT VER_LID(NVRAM_EF_UL1_IOT_CUSTOMIZATION_LID)
     U_sUl1IotCustomSupportStruct *NVRAM_EF_UL1_IOT_CUSTOMIZATION_TOTAL
     {
         ADAPT_Customized:""
         {
         };
         reserved1:""
         {
         };
         reserved2:""
         {
         };
         reserved3:""
         {
         };
     };
#endif /* #if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__) */

#if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__) 
LID_BIT VER_LID(NVRAM_EF_UL1_HSPA_CATEGORY_LID)
   nvram_ef_ul1_hspa_category_struct * NVRAM_EF_UL1_HSPA_CATEGORY_TOTAL
   {
      dpa_cat:""
      {
      };
      upa_cat:""
      {
      };
   };
#endif /* #if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__) */

#if defined (__MTK_UL1_FDD__)
LID_BIT VER_LID(NVRAM_EF_UL1_LOW_POWER_LID)
   nvram_ef_ul1_low_power_category_struct * NVRAM_EF_UL1_LOW_POWER_TOTAL
   {
      arx_enable:""
      {
      };
      lorx_enable:""
      {
      };
      lorx_debug_enable:""
      {
      };
   };
   
LID_BIT VER_LID(NVRAM_EF_UL1_RAS_PARAMETER_LID)
   nvram_ef_umts_ul1_ras_struct * NVRAM_EF_UL1_RAS_PARAMETER_TOTAL
   {
      umtsRASFeatureOn:""
      {
      };
      RssiS2WThrdBm:""
      {
      };
      RssiW2SThrdBm:""
      {
      };
      EcnoS2WThrdB:""
      {
      };
      EcnoW2SThrdB:""
      {
      };
      RscpS2WThrdB:""
      {
      };
      RscpW2SThrdB:""
      {
      };
      BothAntforTestSimPS:""
      {
      };
      HsRateHystPercentage:""
      {
      };
      CqiHystIdx:""
      {
      };
      HsRateThrPercentage:""
      {
      };
      CqiDiffThrIdx:""
      {
      };
   };
   
LID_BIT VER_LID(NVRAM_EF_UL1_HS_PATCH_LID)
   nvram_ef_ul1_hs_patch_struct * NVRAM_EF_UL1_HS_PATCH_TOTAL
   {
      hs_patch_enable:""
      {
      };
   };

#endif   //#if defined (__MTK_UL1_FDD__)

/* TX PRACH TM Comp.  (for MT6572,MT6582) */
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND1_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND2_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND3_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND4_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND5_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND6_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND7_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND8_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND9_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND10_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {
     
     };
     
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND11_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {
     
     };
     
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPRACHTMCOMP_BAND19_LID)
     ul1cal_txPrachTmCompData_T *NVRAM_EF_UL1_TXPRACHTMCOMP_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_AFCDAC_LID)
     ul1cal_afcDacData_T *NVRAM_EF_UL1_AFCDAC_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_AFCCAP_LID)
     ul1cal_afcCapData_T *NVRAM_EF_UL1_AFCCAP_TOTAL
     {
     
     };

#if (IS_3G_MIPI_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TPC_HIGHBAND1_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TPC_HIGHBAND2_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TPC_HIGHBAND3_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TPC_LOWBAND1_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TPC_LOWBAND2_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_TPC_BAND_TOTAL
     {
     
     };
#endif

#if (IS_3G_MIPI_NVRAM_FULL_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_EVENT_HIGHBAND1_LID)
     ul1mipi_rxEvent_T *NVRAM_EF_UL1_MIPI_RX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_EVENT_HIGHBAND2_LID)
     ul1mipi_rxEvent_T *NVRAM_EF_UL1_MIPI_RX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_EVENT_HIGHBAND3_LID)
     ul1mipi_rxEvent_T *NVRAM_EF_UL1_MIPI_RX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_EVENT_LOWBAND1_LID)
     ul1mipi_rxEvent_T *NVRAM_EF_UL1_MIPI_RX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_EVENT_LOWBAND2_LID)
     ul1mipi_rxEvent_T *NVRAM_EF_UL1_MIPI_RX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_DATA_HIGHBAND1_LID)
     ul1mipi_rxData_T *NVRAM_EF_UL1_MIPI_RX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_DATA_HIGHBAND2_LID)
     ul1mipi_rxData_T *NVRAM_EF_UL1_MIPI_RX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_DATA_HIGHBAND3_LID)
     ul1mipi_rxData_T *NVRAM_EF_UL1_MIPI_RX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_DATA_LOWBAND1_LID)
     ul1mipi_rxData_T *NVRAM_EF_UL1_MIPI_RX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_RX_DATA_LOWBAND2_LID)
     ul1mipi_rxData_T *NVRAM_EF_UL1_MIPI_RX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_EVENT_HIGHBAND1_LID)
     ul1mipi_txEvent_T *NVRAM_EF_UL1_MIPI_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_EVENT_HIGHBAND2_LID)
     ul1mipi_txEvent_T *NVRAM_EF_UL1_MIPI_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_EVENT_HIGHBAND3_LID)
     ul1mipi_txEvent_T *NVRAM_EF_UL1_MIPI_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_EVENT_LOWBAND1_LID)
     ul1mipi_txEvent_T *NVRAM_EF_UL1_MIPI_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_EVENT_LOWBAND2_LID)
     ul1mipi_txEvent_T *NVRAM_EF_UL1_MIPI_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_DATA_HIGHBAND1_LID)
     ul1mipi_txData_T *NVRAM_EF_UL1_MIPI_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_DATA_HIGHBAND2_LID)
     ul1mipi_txData_T *NVRAM_EF_UL1_MIPI_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_DATA_HIGHBAND3_LID)
     ul1mipi_txData_T *NVRAM_EF_UL1_MIPI_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_DATA_LOWBAND1_LID)
     ul1mipi_txData_T *NVRAM_EF_UL1_MIPI_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_TX_DATA_LOWBAND2_LID)
     ul1mipi_txData_T *NVRAM_EF_UL1_MIPI_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ASM_ISOLATION_HIGHBAND1_LID)
     ul1mipi_asmIsoData_T *NVRAM_EF_UL1_MIPI_ASM_ISOLATION_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ASM_ISOLATION_HIGHBAND2_LID)
     ul1mipi_asmIsoData_T *NVRAM_EF_UL1_MIPI_ASM_ISOLATION_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ASM_ISOLATION_HIGHBAND3_LID)
     ul1mipi_asmIsoData_T *NVRAM_EF_UL1_MIPI_ASM_ISOLATION_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ASM_ISOLATION_LOWBAND1_LID)
     ul1mipi_asmIsoData_T *NVRAM_EF_UL1_MIPI_ASM_ISOLATION_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ASM_ISOLATION_LOWBAND2_LID)
     ul1mipi_asmIsoData_T *NVRAM_EF_UL1_MIPI_ASM_ISOLATION_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_INIT_CW_LID)
     ul1mipi_initCwData_T *NVRAM_EF_UL1_MIPI_INIT_CW_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_SLEEP_CW_LID)
     ul1mipi_sleepCwData_T *NVRAM_EF_UL1_MIPI_SLEEP_CW_TOTAL
     {
     
     };
#endif/*IS_3G_MIPI_NVRAM_FULL_SUPPORT*/

#if (IS_3G_VPA_SEL_BY_BAND_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_VPA_SRC_SEL_HIGHBAND1_LID)
     ul1vpa_sel_T *NVRAM_EF_UL1_VPA_SRC_SEL_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_VPA_SRC_SEL_HIGHBAND2_LID)
     ul1vpa_sel_T *NVRAM_EF_UL1_VPA_SRC_SEL_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_VPA_SRC_SEL_HIGHBAND3_LID)
     ul1vpa_sel_T *NVRAM_EF_UL1_VPA_SRC_SEL_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_VPA_SRC_SEL_LOWBAND1_LID)
     ul1vpa_sel_T *NVRAM_EF_UL1_VPA_SRC_SEL_BAND_TOTAL
     {
     
     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_VPA_SRC_SEL_LOWBAND2_LID)
     ul1vpa_sel_T *NVRAM_EF_UL1_VPA_SRC_SEL_BAND_TOTAL
     {
     
     };
#endif/*IS_3G_VPA_SEL_BY_BAND_SUPPORT*/

#if IS_3G_TAS_UL1_CUSTOM_SUPPORT
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_FEATURE_BY_RAT_LID)
     UMTS_CUSTOM_TAS_FEATURE_BY_RAT_T *NVRAM_EF_UL1_TAS_FEATURE_BY_RAT_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_FE_ROUTE_DATABASE_LID)
     UMTS_CUSTOM_TAS_FE_ROUTE_DATABASE_T *NVRAM_EF_UL1_TAS_FE_ROUTE_DATABASE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_FE_DATABASE_LID)
     UMTS_CUSTOM_TAS_FE_DATABASE_T *NVRAM_EF_UL1_TAS_FE_DATABASE_TOTAL
     {

     };
#if (IS_3G_MIPI_NVRAM_FULL_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_A_MIPI_EVENT_LID)
     ul1mipi_tasEvent_CatA_T *NVRAM_EF_UL1_CAT_A_TAS_MIPI_EVT_ROUTE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_A_MIPI_DATA_LID)
     ul1mipi_tasData_CatA_T *NVRAM_EF_UL1_CAT_A_TAS_MIPI_DATA_ROUTE_TOTAL
     {

     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_B_MIPI_EVENT_LID)
     ul1mipi_tasEvent_CatB_T *NVRAM_EF_UL1_CAT_B_TAS_MIPI_EVT_ROUTE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_B_MIPI_DATA_LID)
     ul1mipi_tasData_CatB_T *NVRAM_EF_UL1_CAT_B_TAS_MIPI_DATA_ROUTE_TOTAL
     {

     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_C_MIPI_EVENT_LID)
     ul1mipi_tasEvent_CatC_T *NVRAM_EF_UL1_CAT_C_TAS_MIPI_EVT_ROUTE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TAS_CAT_C_MIPI_DATA_LID)
     ul1mipi_tasData_CatC_T *NVRAM_EF_UL1_CAT_C_TAS_MIPI_DATA_ROUTE_TOTAL
     {

     };
#endif
#endif
#if IS_3G_DAT_UL1_CUSTOM_SUPPORT
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_FEATURE_BY_RAT_LID)
     UMTS_CUSTOM_DAT_FEATURE_BY_RAT_T *NVRAM_EF_UL1_DAT_FEATURE_BY_RAT_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_FE_ROUTE_DATABASE_LID)
     UMTS_CUSTOM_DAT_FE_ROUTE_DATABASE_T *NVRAM_EF_UL1_DAT_FE_ROUTE_DATABASE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_FE_DATABASE_LID)
     UMTS_CUSTOM_DAT_FE_DATABASE_T *NVRAM_EF_UL1_DAT_FE_DATABASE_TOTAL
     {

     };
#if (IS_3G_MIPI_NVRAM_FULL_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_CAT_A_MIPI_EVENT_LID)
     ul1mipi_datEvent_CatA_T *NVRAM_EF_UL1_CAT_A_DAT_MIPI_EVT_ROUTE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_CAT_A_MIPI_DATA_LID)
     ul1mipi_datData_CatA_T *NVRAM_EF_UL1_CAT_A_DAT_MIPI_DATA_ROUTE_TOTAL
     {

     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_CAT_B_MIPI_EVENT_LID)
     ul1mipi_datEvent_CatB_T *NVRAM_EF_UL1_CAT_B_DAT_MIPI_EVT_ROUTE_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DAT_CAT_B_MIPI_DATA_LID)
     ul1mipi_datData_CatB_T *NVRAM_EF_UL1_CAT_B_DAT_MIPI_DATA_ROUTE_TOTAL
     {

     };

#endif
#endif
#if (IS_3G_TX_POWER_OFFSET_SUPPORT || IS_3G_SAR_TX_POWER_BACKOFF_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPOWEROFFSET_HIGHBAND1_LID)
     U_sTXPOWEROFFSETDATA *NVRAM_EF_UL1_TXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPOWEROFFSET_HIGHBAND2_LID)
     U_sTXPOWEROFFSETDATA *NVRAM_EF_UL1_TXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPOWEROFFSET_HIGHBAND3_LID)
     U_sTXPOWEROFFSETDATA *NVRAM_EF_UL1_TXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPOWEROFFSET_LOWBAND1_LID)
     U_sTXPOWEROFFSETDATA *NVRAM_EF_UL1_TXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPOWEROFFSET_LOWBAND2_LID)
     U_sTXPOWEROFFSETDATA *NVRAM_EF_UL1_TXPOWEROFFSET_BAND_TOTAL
     {
     
     };
#endif   /* IS_3G_TX_POWER_OFFSET_SUPPORT */
#if (IS_3G_RX_POWER_OFFSET_SUPPORT )
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RXPOWEROFFSET_HIGHBAND1_LID)
     U_sRXPOWEROFFSETDATA *NVRAM_EF_UL1_RXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RXPOWEROFFSET_HIGHBAND2_LID)
     U_sRXPOWEROFFSETDATA *NVRAM_EF_UL1_RXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RXPOWEROFFSET_HIGHBAND3_LID)
     U_sRXPOWEROFFSETDATA *NVRAM_EF_UL1_RXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RXPOWEROFFSET_LOWBAND1_LID)
     U_sRXPOWEROFFSETDATA *NVRAM_EF_UL1_RXPOWEROFFSET_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RXPOWEROFFSET_LOWBAND2_LID)
     U_sRXPOWEROFFSETDATA *NVRAM_EF_UL1_RXPOWEROFFSET_BAND_TOTAL
     {
     
     };
#endif   /* IS_3G_RX_POWER_OFFSET_SUPPORT */

#if (IS_3G_RFEQ_COEF_SUBBAND_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_COEF_HIGHBAND1_LID)
     hs_dsch_rfeq_info_band_T *NVRAM_EF_UL1_RFEQ_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_COEF_HIGHBAND2_LID)
     hs_dsch_rfeq_info_band_T *NVRAM_EF_UL1_RFEQ_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_COEF_HIGHBAND3_LID)
     hs_dsch_rfeq_info_band_T *NVRAM_EF_UL1_RFEQ_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_COEF_LOWBAND1_LID)
     hs_dsch_rfeq_info_band_T *NVRAM_EF_UL1_RFEQ_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_COEF_LOWBAND2_LID)
     hs_dsch_rfeq_info_band_T *NVRAM_EF_UL1_RFEQ_COEF_BAND_TOTAL
     {
     
     };
#endif   /* IS_3G_RFEQ_COEF_SUBBAND_SUPPORT */

#if (IS_3G_RFEQ_REAL_COEF_TEST)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_REAL_COEF_HIGHBAND1_LID)
     URXDFE_REAL_RFEQ_CUSTOM_BAND_T *NVRAM_EF_UL1_RFEQ_REAL_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_REAL_COEF_HIGHBAND2_LID)
     URXDFE_REAL_RFEQ_CUSTOM_BAND_T *NVRAM_EF_UL1_RFEQ_REAL_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_REAL_COEF_HIGHBAND3_LID)
     URXDFE_REAL_RFEQ_CUSTOM_BAND_T *NVRAM_EF_UL1_RFEQ_REAL_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_REAL_COEF_LOWBAND1_LID)
     URXDFE_REAL_RFEQ_CUSTOM_BAND_T *NVRAM_EF_UL1_RFEQ_REAL_COEF_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_RFEQ_REAL_COEF_LOWBAND2_LID)
     URXDFE_REAL_RFEQ_CUSTOM_BAND_T *NVRAM_EF_UL1_RFEQ_REAL_COEF_BAND_TOTAL
     {
     
     };
#endif   /* IS_3G_RFEQ_REAL_COEF_TEST */


LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND1_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND2_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND3_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND4_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND5_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND6_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND7_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND8_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND9_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND10_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND11_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PWRONCAL_BAND19_LID)
     UMTS_RF_POWER_ON_CAL_DATA_PER_BAND_T *NVRAM_EF_UL1_PWRONCAL_TOTAL
     {

   };

#if defined(__UMTS_RAT__) && defined(__MTK_UL1_FDD__)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TEMP_DAC_LID)
     ul1cal_tempdacData_T *NVRAM_EF_UL1_TEMP_DAC_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND1_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND2_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND3_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND4_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND5_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND6_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND7_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND8_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND9_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND10_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND11_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS_BAND19_LID)
     ul1cal_pathlossData_T *NVRAM_EF_UL1_PATHLOSS_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND1_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND2_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND3_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND4_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND5_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND6_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND7_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND8_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND9_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND10_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND11_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXDAC_BAND19_LID)
     ul1cal_txdacData_T *NVRAM_EF_UL1_TXDAC_BAND_TOTAL
     {

     };
#endif /* __UMTS_RAT__ && __MTK_UL1_FDD__ */

#if defined (__MTK_UL1_FDD__)
   #if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__)
/* PA 8-level control (for MT6276, MT6573) */
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND1_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND2_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND3_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND4_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND5_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND6_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND7_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND8_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND9_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND10_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND11_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPAOCTLEV_BAND19_LID)
     ul1cal_txPaOctLevData_T *NVRAM_EF_UL1_TXPAOCTLEV_BAND_TOTAL
     {

     };
   #endif // #if defined (__UL1_HS_PLATFORM__) || defined (__UL1_HS_PLUS_PLATFORM__)

   #if defined(__UMTS_R8__)
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND1_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND2_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND3_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND4_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND5_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND6_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND7_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND8_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND9_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND10_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND11_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_PATHLOSS2_BAND19_LID)
        ul1cal_pathlossRxdData_T *NVRAM_EF_UL1_PATHLOSS2_BAND_TOTAL
        {

      };

   // add by Wilson
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND1_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND2_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND3_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND4_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND5_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND6_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND7_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND8_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND9_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND10_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND11_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_TXPADRIFTCOMP_BAND19_LID)
        ul1cal_txPaDriftCompData_T *NVRAM_EF_UL1_TXPADRIFTCOMP_BAND_TOTAL
        {

      };
   #endif

LID_BIT VER_LID(NVRAM_EF_UL1_TAS_THRESHOLD_LID)
     nvram_ef_umts_tas_thr_struct * NVRAM_EF_UL1_TAS_THRESHOLD_TOTAL
     {
        rscp_diff_thd_rp:""
        {
        };
        rscp_diff_thd_po:""
        {
        };
        rscp_diff_thd_txp:""
        {
        };
        rscp_diff_thd_cb:""
        {
        };
        tas_type2_blind_switch_init_thd1:""
        {
        };
        tas_type2_blind_switch_step_size:""
        {
        };
        tas_type2_blind_switch_uppBound:""
        {
        };
        tas_type2_rscp_switch_back_thd:""
        {
        };
     };
#endif // #if defined (__MTK_UL1_FDD__)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CTRL_DATA_HIGHBAND1_LID)
        U_sDPD_COMMON_CTRL *NVRAM_EF_UL1_DPD_CTRL_DATA_TOTAL{

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CTRL_DATA_HIGHBAND2_LID)
     U_sDPD_COMMON_CTRL *NVRAM_EF_UL1_DPD_CTRL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CTRL_DATA_HIGHBAND3_LID)
     U_sDPD_COMMON_CTRL *NVRAM_EF_UL1_DPD_CTRL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CTRL_DATA_LOWBAND1_LID)
     U_sDPD_COMMON_CTRL *NVRAM_EF_UL1_DPD_CTRL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CTRL_DATA_LOWBAND2_LID)
     U_sDPD_COMMON_CTRL *NVRAM_EF_UL1_DPD_CTRL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CAL_DATA_HIGHBAND1_LID)
     U_sDPD_GROUP_CAL *NVRAM_EF_UL1_DPD_CAL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CAL_DATA_HIGHBAND2_LID)
     U_sDPD_GROUP_CAL *NVRAM_EF_UL1_DPD_CAL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CAL_DATA_HIGHBAND3_LID)
     U_sDPD_GROUP_CAL *NVRAM_EF_UL1_DPD_CAL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CAL_DATA_LOWBAND1_LID)
     U_sDPD_GROUP_CAL *NVRAM_EF_UL1_DPD_CAL_DATA_TOTAL
     {


   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_CAL_DATA_LOWBAND2_LID)
     U_sDPD_GROUP_CAL *NVRAM_EF_UL1_DPD_CAL_DATA_TOTAL
     {

   };
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_DPD_PARAMETER_LID)
     U_sUl1dDpdCustomInputData *NVRAM_EF_UL1_DPD_PARAMETER_TOTAL
     {

   };
#if (IS_3G_MIPI_SUPPORT)
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_DPD_TPC_HIGHBAND1_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_DPD_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_DPD_TPC_HIGHBAND2_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_DPD_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_DPD_TPC_HIGHBAND3_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_DPD_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_DPD_TPC_LOWBAND1_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_DPD_TPC_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_DPD_TPC_LOWBAND2_LID)
     ul1mipi_tpcData_T *NVRAM_EF_UL1_MIPI_DPD_TPC_BAND_TOTAL
     {
     
     };

#if __IS_UL1D_ETM_SUPPORT__
LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_EVENT_HIGHBAND1_LID)
     ul1mipiEtm_txEvent_T *NVRAM_EF_UL1_MIPI_ETM_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_EVENT_HIGHBAND2_LID)
     ul1mipiEtm_txEvent_T *NVRAM_EF_UL1_MIPI_ETM_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_EVENT_HIGHBAND3_LID)
     ul1mipiEtm_txEvent_T *NVRAM_EF_UL1_MIPI_ETM_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_EVENT_LOWBAND1_LID)
     ul1mipiEtm_txEvent_T *NVRAM_EF_UL1_MIPI_ETM_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_EVENT_LOWBAND2_LID)
     ul1mipiEtm_txEvent_T *NVRAM_EF_UL1_MIPI_ETM_TX_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_DATA_HIGHBAND1_LID)
     ul1mipiEtm_txData_T *NVRAM_EF_UL1_MIPI_ETM_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_DATA_HIGHBAND2_LID)
     ul1mipiEtm_txData_T *NVRAM_EF_UL1_MIPI_ETM_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_DATA_HIGHBAND3_LID)
     ul1mipiEtm_txData_T *NVRAM_EF_UL1_MIPI_ETM_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_DATA_LOWBAND1_LID)
     ul1mipiEtm_txData_T *NVRAM_EF_UL1_MIPI_ETM_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TX_DATA_LOWBAND2_LID)
     ul1mipiEtm_txData_T *NVRAM_EF_UL1_MIPI_ETM_TX_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_EVENT_HIGHBAND1_LID)
     ul1mipiEtm_tpcEvent_T *NVRAM_EF_UL1_MIPI_ETM_TPC_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_EVENT_HIGHBAND2_LID)
     ul1mipiEtm_tpcEvent_T *NVRAM_EF_UL1_MIPI_ETM_TPC_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_EVENT_HIGHBAND3_LID)
     ul1mipiEtm_tpcEvent_T *NVRAM_EF_UL1_MIPI_ETM_TPC_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_EVENT_LOWBAND1_LID)
     ul1mipiEtm_tpcEvent_T *NVRAM_EF_UL1_MIPI_ETM_TPC_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_EVENT_LOWBAND2_LID)
     ul1mipiEtm_tpcEvent_T *NVRAM_EF_UL1_MIPI_ETM_TPC_EVT_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_HIGHBAND1_LID)
     ul1mipiEtm_tpcData_T *NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_HIGHBAND2_LID)
     ul1mipiEtm_tpcData_T *NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_HIGHBAND3_LID)
     ul1mipiEtm_tpcData_T *NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_LOWBAND1_LID)
     ul1mipiEtm_tpcData_T *NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_BAND_TOTAL
     {
     
     };

LID_BIT MULTIPLE_LID VER_LID(NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_LOWBAND2_LID)
     ul1mipiEtm_tpcData_T *NVRAM_EF_UL1_MIPI_ETM_TPC_DATA_BAND_TOTAL
     {
     
     };
#endif   // #if __IS_UL1D_ETM_SUPPORT__

#endif

END_NVRAM_DATA

#endif  /* GEN_FOR_PC */

#ifdef __cplusplus
}
#endif 

#endif  /* __MTK_UL1_FDD__ */
#endif  /* !NVRAM_NOT_PRESENT */
#endif  /* __UL1_NVRAM_EDITOR_H__ */
